/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicPeriodsRouteImport } from './routes/academic-periods'
import { Route as AcademicRegistrationRouteImport } from './routes/academic-registration'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicPeriodsRoute = AcademicPeriodsRouteImport.update({
  id: '/academic-periods',
  path: '/academic-periods',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRegistrationRoute = AcademicRegistrationRouteImport.update({
  id: '/academic-registration',
  path: '/academic-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-periods': typeof AcademicPeriodsRoute
  '/academic-registration': typeof AcademicRegistrationRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/student': typeof StudentRoute
  '/super-admin': typeof SuperAdminRoute
  '/support': typeof SupportRoute
  '/teacher': typeof TeacherRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-periods': typeof AcademicPeriodsRoute
  '/academic-registration': typeof AcademicRegistrationRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/student': typeof StudentRoute
  '/super-admin': typeof SuperAdminRoute
  '/support': typeof SupportRoute
  '/teacher': typeof TeacherRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-periods': typeof AcademicPeriodsRoute
  '/academic-registration': typeof AcademicRegistrationRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/roles': typeof RolesRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/student': typeof StudentRoute
  '/super-admin': typeof SuperAdminRoute
  '/support': typeof SupportRoute
  '/teacher': typeof TeacherRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-periods'
    | '/academic-registration'
    | '/admin'
    | '/assets'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/customer'
    | '/dashboard'
    | '/facilities'
    | '/gallery'
    | '/operations'
    | '/reports'
    | '/reviews'
    | '/roles'
    | '/services'
    | '/shop'
    | '/student'
    | '/super-admin'
    | '/support'
    | '/teacher'
    | '/verify-certificate'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-periods'
    | '/academic-registration'
    | '/admin'
    | '/assets'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/customer'
    | '/dashboard'
    | '/facilities'
    | '/gallery'
    | '/operations'
    | '/reports'
    | '/reviews'
    | '/roles'
    | '/services'
    | '/shop'
    | '/student'
    | '/super-admin'
    | '/support'
    | '/teacher'
    | '/verify-certificate'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-periods'
    | '/academic-registration'
    | '/admin'
    | '/assets'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/customer'
    | '/dashboard'
    | '/facilities'
    | '/gallery'
    | '/operations'
    | '/reports'
    | '/reviews'
    | '/roles'
    | '/services'
    | '/shop'
    | '/student'
    | '/super-admin'
    | '/support'
    | '/teacher'
    | '/verify-certificate'
    | '/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicPeriodsRoute: typeof AcademicPeriodsRoute
  AcademicRegistrationRoute: typeof AcademicRegistrationRoute
  AdminRoute: typeof AdminRoute
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  CustomerRoute: typeof CustomerRoute
  DashboardRoute: typeof DashboardRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  OperationsRoute: typeof OperationsRoute
  ReportsRoute: typeof ReportsRoute
  ReviewsRoute: typeof ReviewsRoute
  RolesRoute: typeof RolesRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  StudentRoute: typeof StudentRoute
  SuperAdminRoute: typeof SuperAdminRoute
  SupportRoute: typeof SupportRoute
  TeacherRoute: typeof TeacherRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-periods': {
      id: '/academic-periods'
      path: '/academic-periods'
      fullPath: '/academic-periods'
      preLoaderRoute: typeof AcademicPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-registration': {
      id: '/academic-registration'
      path: '/academic-registration'
      fullPath: '/academic-registration'
      preLoaderRoute: typeof AcademicRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicPeriodsRoute: AcademicPeriodsRoute,
  AcademicRegistrationRoute: AcademicRegistrationRoute,
  AdminRoute: AdminRoute,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  CustomerRoute: CustomerRoute,
  DashboardRoute: DashboardRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  OperationsRoute: OperationsRoute,
  ReportsRoute: ReportsRoute,
  ReviewsRoute: ReviewsRoute,
  RolesRoute: RolesRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  StudentRoute: StudentRoute,
  SuperAdminRoute: SuperAdminRoute,
  SupportRoute: SupportRoute,
  TeacherRoute: TeacherRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
